<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PC201710171401" name="com.testng.testng.api.APITest" tests="4" failures="1" timestamp="29 十二月 2018 08:26:34 GMT" time="0.279" errors="0">
  <testcase name="f" time="0.030" classname="com.testng.testng.api.APITest">
    <failure type="java.lang.AssertionError" message="expected [{&quot;body&quot;:{&quot;result&quot;:{&quot;user&quot;:&quot;testname&quot;,&quot;pwd&quot;:&quot;000000&quot;}},&quot;status&quot;:&quot;成功&quot;}] but found [{&quot;body&quot;:{&quot;result&quot;:&quot;换个用户名&quot;},&quot;status&quot;:&quot;失败&quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"body":{"result":{"user":"testname","pwd":"000000"}},"status":"成功"}] but found [{"body":{"result":"换个用户名"},"status":"失败"}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testng.api.APITest.doCase(APITest.java:38)
at com.testng.testng.api.APITest.f(APITest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.110" classname="com.testng.testng.api.APITest"/>
  <testcase name="f" time="0.006" classname="com.testng.testng.api.APITest"/>
  <testcase name="f" time="0.133" classname="com.testng.testng.api.APITest"/>
</testsuite> <!-- com.testng.testng.api.APITest -->
